export const mediaEvents = [
    {
        id: 'prime-award',
        title: "Rajendra Singh Rajput Honored by Chirag Paswan with Prime of Central India Award",
        description: "A proud moment for DCT Real Estate as our founder, Mr. Rajendra Singh Rajput, was honored with the 'Prime of Central India Award' by Shri Chirag Paswan. This recognition celebrates his visionary leadership and our team's commitment to transforming Central India's real estate landscape through quality and innovation.",
        images: [
            "/images/events/award/IMG-20250114-WA0039.jpg",
            "/images/events/award/dc1.jpg",
            "/images/events/award/dc2.jpg",
            "/images/events/award/dc3.jpg",
            "/images/events/award/dct.jpg",
            "/images/events/award/dct4.jpg",
            "/images/events/award/dct5.jpg",
            "/images/events/award/dct6.jpg",
            "/images/events/award/dct8.jpg",
            "/images/events/award/dct10.jpg",
            "/images/events/award/dct16.jpg"
        ]
    },
    {
        id: 'megha-expo-2025',
        title: "Megha Expo 2025",
        description: "DCT Real Estate made a strong impression at Megha Expo 2025, showcasing our diverse portfolio of premium projects. The event provided a perfect platform to present our vision for urban living in Bilaspur, connecting with investors and homebuyers who share our passion for sustainable, world-class developments.",
        images: [
            "/images/events/megha-expo/1.jpg",
            "/images/events/megha-expo/2.jpg",
            "/images/events/megha-expo/3.jpg",
            "/images/events/megha-expo/4.jpg",
            "/images/events/megha-expo/5.jpg",
            "/images/events/megha-expo/6.jpg",
            "/images/events/megha-expo/7.jpg",
            "/images/events/megha-expo/8.jpg",
            "/images/events/megha-expo/9.jpg",
            "/images/events/megha-expo/10.jpg",
            "/images/events/megha-expo/dct-real-estate.jpg",
            "/images/events/megha-expo/dct-real-estate1.jpg",
            "/images/events/megha-expo/dct-real-estate2.jpg",
            "/images/events/megha-expo/dct-real-estate3.jpg",
            "/images/events/megha-expo/dct-real-estate4.jpg",
            "/images/events/megha-expo/dct-real-estate5.jpg",
            "/images/events/megha-expo/dct-real-estate6.jpg",
            "/images/events/megha-expo/dct-real-estate7.jpg",
            "/images/events/megha-expo/dct-real-estate8.jpg",
            "/images/events/megha-expo/dct-real-estate9.jpg",
            "/images/events/megha-expo/dct-real-estate10.jpg",
            "/images/events/megha-expo/dct-real-estate11.jpg",
            "/images/events/megha-expo/dct-real-estate12.jpg",
            "/images/events/megha-expo/dct-real-estate13.jpg",
            "/images/events/megha-expo/dct-real-estate14.jpg",
            "/images/events/megha-expo/dct-real-estate15.jpg",
            "/images/events/megha-expo/dct-real-estate16.jpg",
            "/images/events/megha-expo/dct-real-estate17.jpg",
            "/images/events/megha-expo/dct-real-estate18.jpg",
            "/images/events/megha-expo/dct-real-estate19.jpg",
            "/images/events/megha-expo/dct-real-estate20.jpg",
            "/images/events/megha-expo/dct-real-estate21.jpg",
            "/images/events/megha-expo/dct-real-estate22.jpg",
            "/images/events/megha-expo/dct-real-estate23.jpg",
            "/images/events/megha-expo/dct-real-estate24.jpg",
            "/images/events/megha-expo/dct-real-estate25.jpg",
            "/images/events/megha-expo/dct-real-estate26.jpg"
        ]
    }
];
